const agendamentos = [
  {
    id: "047677522",
    status: "realizado",
    nome: "Hemograma",
    unidade: "Osasco",
    data: "16/11/2022",
    hora: "15:30",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-lab-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "047673486",
    status: "agendado",
    nome: "Colesterol Total",
    unidade: "Osasco",
    data: "20/10/2022",
    hora: "09:15",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-petri-dish-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "047673335",
    status: "cancelado",
    nome: "Colesterol Total",
    unidade: "Osasco",
    data: "16/10/2022",
    hora: "09:00",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-syringes-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "447677522",
    status: "realizado",
    nome: "Hemograma",
    unidade: "Osasco",
    data: "16/11/2022",
    hora: "15:30",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-lab-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "247673486",
    status: "agendado",
    nome: "Colesterol Total",
    unidade: "Osasco",
    data: "20/10/2022",
    hora: "09:15",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-petri-dish-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "147673335",
    status: "cancelado",
    nome: "Colesterol Total",
    unidade: "Osasco",
    data: "16/10/2022",
    hora: "09:00",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-syringes-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "447117522",
    status: "realizado",
    nome: "Hemograma",
    unidade: "Osasco",
    data: "16/11/2022",
    hora: "15:30",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-lab-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "217673486",
    status: "agendado",
    nome: "Colesterol Total",
    unidade: "Osasco",
    data: "20/10/2022",
    hora: "09:15",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-petri-dish-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
  {
    id: "147673355",
    status: "cancelado",
    nome: "Colesterol Total",
    unidade: "Osasco",
    data: "16/10/2022",
    hora: "09:00",
    icon: "https://img.icons8.com/external-xnimrodx-lineal-color-xnimrodx/512/external-syringes-virus-xnimrodx-lineal-color-xnimrodx.png",
  },
];

export default agendamentos;
